/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

/**
 *
 * @author HaqHfz
 */
public class ManagerUI extends javax.swing.JFrame {

    /**
     * Creates new form ManagerUI
     */
    public ManagerUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        graphContainer = new javax.swing.JPanel();
        panel_Manager_Filter = new javax.swing.JPanel();
        lbl_Manager_Network = new javax.swing.JLabel();
        lbl_Manager_Route = new javax.swing.JLabel();
        cmb_Manager_Network = new javax.swing.JComboBox<>();
        cmb_Manager_Route = new javax.swing.JComboBox<>();
        lbl_Manager_StartTime = new javax.swing.JLabel();
        lbl_Manager_EndTime = new javax.swing.JLabel();
        lbl_Manager_Note = new javax.swing.JLabel();
        btn_Manager_Filter1 = new javax.swing.JButton();
        btn_Manager_Filter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_Manager_Filter.setLayout(null);

        lbl_Manager_Network.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_Manager_Network.setText("Network :");
        panel_Manager_Filter.add(lbl_Manager_Network);
        lbl_Manager_Network.setBounds(20, 90, 80, 20);

        lbl_Manager_Route.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_Manager_Route.setText("Route :");
        panel_Manager_Filter.add(lbl_Manager_Route);
        lbl_Manager_Route.setBounds(20, 140, 70, 17);

        cmb_Manager_Network.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmb_Manager_Network.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_Manager_NetworkrefreshRoutes(evt);
            }
        });
        panel_Manager_Filter.add(cmb_Manager_Network);
        cmb_Manager_Network.setBounds(110, 90, 130, 20);

        cmb_Manager_Route.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panel_Manager_Filter.add(cmb_Manager_Route);
        cmb_Manager_Route.setBounds(110, 140, 130, 20);

        lbl_Manager_StartTime.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_Manager_StartTime.setText("Start Time :");
        panel_Manager_Filter.add(lbl_Manager_StartTime);
        lbl_Manager_StartTime.setBounds(20, 190, 90, 20);

        lbl_Manager_EndTime.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_Manager_EndTime.setText("End Time :");
        panel_Manager_Filter.add(lbl_Manager_EndTime);
        lbl_Manager_EndTime.setBounds(20, 240, 80, 17);

        lbl_Manager_Note.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_Manager_Note.setText("Select Filters");
        panel_Manager_Filter.add(lbl_Manager_Note);
        lbl_Manager_Note.setBounds(90, 30, 90, 20);

        btn_Manager_Filter1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_Manager_Filter1.setText("Filter");
        btn_Manager_Filter1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Manager_Filter1ActionPerformed(evt);
            }
        });
        panel_Manager_Filter.add(btn_Manager_Filter1);
        btn_Manager_Filter1.setBounds(170, 330, 71, 31);

        btn_Manager_Filter.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_Manager_Filter.setText("ADD Route");
        btn_Manager_Filter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Manager_FilterActionPerformed(evt);
            }
        });
        panel_Manager_Filter.add(btn_Manager_Filter);
        btn_Manager_Filter.setBounds(20, 330, 120, 31);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_Manager_Filter, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(graphContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(graphContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_Manager_Filter, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_Manager_NetworkrefreshRoutes(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_Manager_NetworkrefreshRoutes
        // TODO add your handling code here:
//        loadRoutes();
    }//GEN-LAST:event_cmb_Manager_NetworkrefreshRoutes

    private void btn_Manager_FilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Manager_FilterActionPerformed
        // TODO add your handling code here:
        //        if (cmb_Manager_Network.getSelectedItem() == null) {
            //            JOptionPane.showMessageDialog(null, "Please select a Network", "Error", JOptionPane.PLAIN_MESSAGE);
            //        } else if (cmb_Manager_Route.getSelectedItem() == null) {
            //            JOptionPane.showMessageDialog(null, "Please select a Route", "Error", JOptionPane.PLAIN_MESSAGE);
            //        } else if (dtp_Manager_StartTime.getDate() == null) {
            //            JOptionPane.showMessageDialog(null, "Please select a start Date", "Error", JOptionPane.PLAIN_MESSAGE);
            //        } else if (dtp_Manager_EndTime.getDate() == null) {
            //            JOptionPane.showMessageDialog(null, "Please select an end Date", "Error", JOptionPane.PLAIN_MESSAGE);
            //        } else {
            //            filterRecords();
            //        }
    }//GEN-LAST:event_btn_Manager_FilterActionPerformed

    private void btn_Manager_Filter1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Manager_Filter1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Manager_Filter1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Manager_Filter;
    private javax.swing.JButton btn_Manager_Filter1;
    private javax.swing.JComboBox<String> cmb_Manager_Network;
    private javax.swing.JComboBox<String> cmb_Manager_Route;
    private javax.swing.JPanel graphContainer;
    private javax.swing.JLabel lbl_Manager_EndTime;
    private javax.swing.JLabel lbl_Manager_Network;
    private javax.swing.JLabel lbl_Manager_Note;
    private javax.swing.JLabel lbl_Manager_Route;
    private javax.swing.JLabel lbl_Manager_StartTime;
    private javax.swing.JPanel panel_Manager_Filter;
    // End of variables declaration//GEN-END:variables
}
